### ISSUE TITLE
'sha1_rotl' was not declared in this scope

### ISSUE THREAD

**Issue by icetinturkey** [daknuett/cryptosuite2#11]
![sha-error-1](https://user-images.githubusercontent.com/41130134/58972620-a1d6e400-87c6-11e9-879f-ae1d9f90361d.jpg)

**Comment by daknuett** [comment]
I can reprodice the problem. I am on it.

**Comment by daknuett** [comment]
The bug appears to be mainly related to Arduino's broken build system. I will push a work-around, because there is no way to really fix this for me.

**Comment by daknuett** [comment]
Nevermind. It is a bug in related to my workaround of Arduino's broken build system.

Pushing fix now.
