### ISSUE TITLE
Add example programs for Arduino

### ISSUE THREAD

**Issue by daknuett** [daknuett/cryptosuite2#2]
Add example programs for arduino (under the path `sha/examples`).

Some examples can be copied from the documentation.

**Comment by daknuett** [comment]
I added the example code under `sha/examples` however the Arduino IDE does not show them in the menu.

Maybe @per1234 or @q2dg could help with that?

**Comment by q2dg** [comment]
@daknuett Sorry, I can't. I don't work with Arduino nowadays, sorry

**Comment by daknuett** [comment]
Thank you very much for your work, @per1234. Examples are now showing up properly.

**Comment by daknuett** [comment]
No problem. @per1234 fixed it. Thanks for the response.
-- 
Daniel Knüttel <daniel.knuettel@daknuett.eu>
